name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0'

    - name: Install dependencies
      run: flutter pub get
      working-directory: Android-Apps/savourai

    - name: Analyze code
      run: flutter analyze
      working-directory: Android-Apps/savourai

    - name: Run tests
      run: flutter test
      working-directory: Android-Apps/savourai
